development:
  database: mongolog
  capsize: <%= 10.megabytes %>
  host: localhost

<% @uri = URI.parse(ENV['MONGOHQ_URL'] || "mongodb://h:s@f.m.com:27056/app1") %>
production:
  database: <%= @uri.path.sub("/", "") %>
  capsize: <%= 10.megabytes %>
  host: <%= @uri.host %>
  port: <%= @uri.port %>
  username: <%= @uri.user %>
  password: <%= @uri.password %>
