development:
  database: mongolog
  capsize: <%= 10.megabytes %>
  host: localhost

<% ENV['MONGOHQ_URL'] ||= "mongodb://h:s@flame.mongohq.com:27056/app475603" %>
production:
  database: <%= URI.parse(ENV['MONGOHQ_URL']).path.sub("/", "") %>
  capsize: <%= 10.megabytes %>
  host: <%= URI.parse(ENV['MONGOHQ_URL']).host %>
  port: <%= URI.parse(ENV['MONGOHQ_URL']).port %>
  username: <%= URI.parse(ENV['MONGOHQ_URL']).user %>
  password: <%= URI.parse(ENV['MONGOHQ_URL']).password %>
